### ISSUE TITLE
Custom Scrap does not spawn.

### ISSUE THREAD

**Issue by Uborji** [realestudios/CastleGrounds#1]
The custom sm64 scrap doesn't spawn inside the interior - only the vanilla ones do. At first I thought that it was another mod form my pack interfering with scraps spawns, but just to make sure I ended up making a dummy profile on r2modman with only CastleGrounds and it's dependencies only to find it had the same issue there. 

For the dummy profile I made sure to use the default cfgs created by the game on startup, except for Castle Grounds I changed the Content Configuration setting to "true" and Planet Route price to 0.

**Comment by realestudios** [comment]
Did you change the route price or anything in the other pack? I think LLL doesn't catch my scrap spawns for some reason, so if you use it's config file, the scrap spawns get messed up. If that's the case, you'll need to add the CastleGrounds scrap in the LLL config file. I can give you the internal scrap names shortly if this is the case

**Comment by realestudios** [comment]
Three workarounds I have now:

1. Manually add the scrap to the config file you used to change the route price using these names:

CGBobOmbItem
PaintingsCG
CGShellItem
CGStarItem
CGCoinItem
CGRedCoinItem
CGBlueCoinItem
CGBowserKeyItem
CGMIPSItem
CGOneUpItem
CGQBlockItem
CGCapItem

Follow the format for the vanilla scraps (like BobOmbItemCG@15) (higher number means higher chance of a spawn)

2. Add the SM64 Scrap mod and configure it to show up on custom moons (to my knowledge it will show up on all custom moons but I haven't tried adding it to a specific one)

3. Check out LethalQuantities. It's a bit of a bitch to set up, but you can change scrap spawns on each moon that way

**Comment by Uborji** [comment]
I forgot to mention this in my original post, but yes I was using cfg settings under LLL for both the dummy profile I was testing on and the original pack.

The first solution did not work. It seems like the issue happens when I set the content configuration value to "true," which means manually adding scrap in with both the default and internal names doesn't work (This is assuming I did it like I was supposed to. I was adding them under "Scrap Settings - Scrap Spawning List"). Once I set the value back to false the scrap spawned normally, which is great but obviously not ideal since I still wanted to change the other moon settings.

The second solution did work with the settings I wanted thankfully. Unfortunately, I couldn't make it so that the scrap spawned on only the Castle Grounds moon, but this is a suitable alternative for now.

I'll check out the third workaround later when I have more time.



EDIT: Couldn't get lethal quantities to work with my modpack without causing issues. Until a fix is implemented, using the sm64 scrap mod is probably the best solution in my case. Appreciate the help.

**Comment by realestudios** [comment]
Sorry to hear LethalQuantities didn't work. I'm told it could be a bug within LethalLevelLoader itself, but I'm looking into ways to fix it from my end. I will update here if I can get it working

**Comment by realestudios** [comment]
Currently have a fix in the works. Hoping to have it up in a day or two

**Comment by realestudios** [comment]
An [update](https://thunderstore.io/c/lethal-company/p/RealeStudios/CastleGrounds/) has been pushed to the Thunderstore. You can remove the SM64 Scrap mod when the update hits if you don't wish to use it otherwise. After the update, enter these settings into the scrap spawn section of the cfg:

Toilet paper:12,Bottles:4,Tragedy:19,Comedy:21,Stop sign:5,Gold bar:12,Clown horn:9,Airhorn:6,Soccer ball:8,Clock:17,Toy train:8,FancyPaintingCG:20,CGCapItem:30,CGBobOmbItem:25,CGCoinItem:50,CGRedCoinItem:38,CGBlueCoinItem:45,CGQBlockItem:30,CGMIPSItem:10,CGBowserKeyItem:15,CGStarItem:20,CGShellItem:45,CGOneUpItem:40

Feel free to adjust the numbers to your heart's content. 

LLL still doesn't seem to catch the item names for the cfg file automatically, but if you type them in manually or paste the above, it seems to work just fine. Closing the issue as I believe this solves it, but please feel free to open another one if the issue persists
